[package]
name = "aziel/novaly-studios-assignment"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@^1.6"
Promise = "evaera/promise@^4.0"
Signal = "sleitnick/signal@^1.0.1"
ZonePlus = "mattschrubb/zoneplus@3.2.0"
Timer = "sleitnick/timer@1.1.2"
Trove = "sleitnick/trove@1.2.0"